### ISSUE TITLE
UltraFactions not working at all (Still Same Issue)

### ISSUE THREAD

**Issue by Trxgically** [PocketEssential/UltraFaction#18]
Write a short description about the issue

UltraFactions not working at all

Steps to reproduce the issue
How did you find this issue? Did you type a command? Did you simply start your server? What happened? Write steps here.

I added it into the plugin folder, restarted the server then I went to the server and it gave a weird language error on top of the hotbar then I went to the SFTP and It created a folder where all the other server folders are with all it had inside was Languages, Data, Config.json but the languages folder had no data inside and it all created another folder in the plugins folder and it had nothing inside.

OS and versions
UltraFaction Version:
Lastest

Server Software (PM, Genisys etc.)
PM

Machine OS (Linux, Mac, Windows etc.):
Ubuntu

Crashdump, console erros or other info
Was there a crash dump? Was there an error in the console? Is there any other information? Report it here. Please use proper markdown. An example of markdown is provided below.

Copy and paste crash dumps, code blocks, or console errors into here
[15:48:06] [Server thread/INFO]: Enabling UltraFaction v1.0.3
[15:48:06] [Server thread/INFO]: [UltraFaction] -----------------------------
[15:48:06] [Server thread/INFO]: [UltraFaction] - ULTRA FACTION

[15:48:06] [Server thread/INFO]: [UltraFaction] -
[15:48:06] [Server thread/INFO]: [UltraFaction] - Language: eng
[15:48:06] [Server thread/INFO]: [UltraFaction] - Loaded a total of: 0 facti
ons!
[15:48:06] [Server thread/INFO]: [UltraFaction] - Data Provider: Json
[15:48:06] [Server thread/INFO]: [UltraFaction] - Enjoy and stay flexing!
[15:48:06] [Server thread/INFO]: [UltraFaction] -----------------------------
[15:48:06] [Server thread/ERROR]: [UltraFaction] [LANGUAGE] We couldn't find
the language file corresponding to eng. Please make sure eng.json exists

**Comment by xZeroMCPE** [comment]
How are you running `UltraFaction` ?

**Comment by Trxgically** [comment]
What do you mean? Be more specific.

**Comment by xZeroMCPE** [comment]
Are you running it from source code? or a phar

**Comment by Trxgically** [comment]
A phar obviously..

**Comment by Trxgically** [comment]
Whoops but whats your Discord?

**Comment by xZeroMCPE** [comment]
What's yours? I got too many incoming pending requests, you'll get lost in there.

**Comment by ModdingTwins** [comment]
xZero, should i fork it and fix the error? Remember i had the same thing b4.

**Comment by xZeroMCPE** [comment]
I got a new approach to this, I'll update you guys about it on here.

**Comment by xZeroMCPE** [comment]
@Flucid 

Delete `UltraFaction` folder, etc. And grab the latest release and try again.

Let me know if this issue still happens.

**Comment by Trxgically** [comment]
Trxgically#5503

**Comment by ModdingTwins** [comment]
Flucid, please follow direction given above!

**Comment by Trxgically** [comment]
I have already done this he hasn't even posted any new releases the lastest just does the same thing..

**Comment by ModdingTwins** [comment]
Add me on discord ******** and I'll give support

**Comment by Trxgically** [comment]
Discord not found, add me Trxgically#5503

**Comment by xZeroMCPE** [comment]
@Flucid Grab the latest release!

Should be fixed.

**Comment by Flucid** [comment]
Still not working add me on Discord Trxgically#5503 so I can send screenshots.

**Comment by xZeroMCPE** [comment]
Oops

**Comment by ZZWILLIAMXXTrue** [comment]
I have the latest one and it doesn’t work for me
